2015/11/24 13:19:46 [error] [exception.CDbException] could not find driver
2015/11/24 13:19:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in /www/web/default/framework/yii/framework/db/CDbConnection.php:387
Stack trace:
#0 /www/web/default/framework/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /www/web/default/framework/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /www/web/default/framework/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /www/web/default/framework/yii/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(UserMaster))
#7 /www/web/default/appadmin/protected/models/UserMaster.php(127): CActiveRecord::model('UserMaster')
#8 /www/web/default/appadmin/protected/components/UserIdentity.php(22): UserMaster::model()
#9 /www/web/default/appadmin/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /www/web/default/framework/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /www/web/default/framework/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /www/web/default/framework/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /www/web/default/appadmin/protected/controllers/SiteController.php(95): CModel->validate()
#14 /www/web/default/framework/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /www/web/default/framework/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /www/web/default/framework/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /www/web/default/framework/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /www/web/default/framework/yii/framework/web/CWebApplication.php(282): CController->run('login')
#19 /www/web/default/framework/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#20 /www/web/default/framework/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /www/web/default/appadmin/index.php(18): CApplication->run()
#22 {main}
REQUEST_URI=/appadmin/
HTTP_REFERER=http://sigwine.com/appadmin/
---
2015/11/24 13:37:49 [error] [exception.CDbException] could not find driver
2015/11/24 13:37:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in /www/web/default/framework/yii/framework/db/CDbConnection.php:387
Stack trace:
#0 /www/web/default/framework/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /www/web/default/framework/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /www/web/default/framework/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /www/web/default/framework/yii/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(UserMaster))
#7 /www/web/default/appadmin/protected/models/UserMaster.php(127): CActiveRecord::model('UserMaster')
#8 /www/web/default/appadmin/protected/components/UserIdentity.php(22): UserMaster::model()
#9 /www/web/default/appadmin/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /www/web/default/framework/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /www/web/default/framework/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /www/web/default/framework/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /www/web/default/appadmin/protected/controllers/SiteController.php(95): CModel->validate()
#14 /www/web/default/framework/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /www/web/default/framework/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /www/web/default/framework/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /www/web/default/framework/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /www/web/default/framework/yii/framework/web/CWebApplication.php(282): CController->run('login')
#19 /www/web/default/framework/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#20 /www/web/default/framework/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /www/web/default/appadmin/index.php(18): CApplication->run()
#22 {main}
REQUEST_URI=/appadmin/
HTTP_REFERER=http://sigwine.com/appadmin/
---
2015/11/24 13:46:21 [error] [exception.CDbException] could not find driver
2015/11/24 13:46:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in /www/web/default/framework/yii/framework/db/CDbConnection.php:387
Stack trace:
#0 /www/web/default/framework/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /www/web/default/framework/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /www/web/default/framework/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /www/web/default/framework/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /www/web/default/appadmin/protected/controllers/SiteController.php(84): CModule->__get('db')
#5 /www/web/default/framework/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#6 /www/web/default/framework/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /www/web/default/framework/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /www/web/default/framework/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /www/web/default/framework/yii/framework/web/CWebApplication.php(282): CController->run('login')
#10 /www/web/default/framework/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#11 /www/web/default/framework/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#12 /www/web/default/appadmin/index.php(18): CApplication->run()
#13 {main}
REQUEST_URI=/appadmin/
HTTP_REFERER=http://sigwine.com/appadmin/
---
2015/11/24 13:46:59 [error] [exception.CDbException] could not find driver
2015/11/24 13:46:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in /www/web/default/framework/yii/framework/db/CDbConnection.php:387
Stack trace:
#0 /www/web/default/framework/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /www/web/default/framework/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /www/web/default/framework/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /www/web/default/framework/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /www/web/default/appadmin/protected/controllers/SiteController.php(84): CModule->__get('db')
#5 /www/web/default/framework/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#6 /www/web/default/framework/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /www/web/default/framework/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /www/web/default/framework/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /www/web/default/framework/yii/framework/web/CWebApplication.php(282): CController->run('login')
#10 /www/web/default/framework/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#11 /www/web/default/framework/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#12 /www/web/default/appadmin/index.php(18): CApplication->run()
#13 {main}
REQUEST_URI=/appadmin/
HTTP_REFERER=http://sigwine.com/appadmin/
---
2015/11/24 13:49:16 [error] [exception.CDbException] could not find driver
2015/11/24 13:49:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in /www/web/default/framework/yii/framework/db/CDbConnection.php:387
Stack trace:
#0 /www/web/default/framework/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /www/web/default/framework/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /www/web/default/framework/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /www/web/default/framework/yii/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(UserMaster))
#7 /www/web/default/appadmin/protected/models/UserMaster.php(127): CActiveRecord::model('UserMaster')
#8 /www/web/default/appadmin/protected/components/UserIdentity.php(22): UserMaster::model()
#9 /www/web/default/appadmin/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /www/web/default/framework/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /www/web/default/framework/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /www/web/default/framework/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /www/web/default/appadmin/protected/controllers/SiteController.php(114): CModel->validate()
#14 /www/web/default/framework/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /www/web/default/framework/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /www/web/default/framework/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /www/web/default/framework/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /www/web/default/framework/yii/framework/web/CWebApplication.php(282): CController->run('login')
#19 /www/web/default/framework/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#20 /www/web/default/framework/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /www/web/default/appadmin/index.php(18): CApplication->run()
#22 {main}
REQUEST_URI=/appadmin/
HTTP_REFERER=http://sigwine.com/appadmin/
---
2015/11/24 14:57:58 [error] [exception.CDbException] could not find driver
2015/11/24 14:57:58 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in /www/web/default/framework/yii/framework/db/CDbConnection.php:387
Stack trace:
#0 /www/web/default/framework/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /www/web/default/framework/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /www/web/default/framework/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /www/web/default/framework/yii/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(UserMaster))
#7 /www/web/default/appadmin/protected/models/UserMaster.php(127): CActiveRecord::model('UserMaster')
#8 /www/web/default/appadmin/protected/components/UserIdentity.php(22): UserMaster::model()
#9 /www/web/default/appadmin/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /www/web/default/framework/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /www/web/default/framework/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /www/web/default/framework/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /www/web/default/appadmin/protected/controllers/SiteController.php(114): CModel->validate()
#14 /www/web/default/framework/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /www/web/default/framework/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /www/web/default/framework/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /www/web/default/framework/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /www/web/default/framework/yii/framework/web/CWebApplication.php(282): CController->run('login')
#19 /www/web/default/framework/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#20 /www/web/default/framework/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /www/web/default/appadmin/index.php(18): CApplication->run()
#22 {main}
REQUEST_URI=/appadmin/
HTTP_REFERER=http://sigwine.com/appadmin/
---
2015/11/25 17:13:09 [error] [exception.CDbException] could not find driver
2015/11/25 17:13:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in /www/web/default/framework/yii/framework/db/CDbConnection.php:387
Stack trace:
#0 /www/web/default/framework/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /www/web/default/framework/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /www/web/default/framework/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /www/web/default/framework/yii/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(UserMaster))
#7 /www/web/default/appadmin/protected/models/UserMaster.php(127): CActiveRecord::model('UserMaster')
#8 /www/web/default/appadmin/protected/components/UserIdentity.php(22): UserMaster::model()
#9 /www/web/default/appadmin/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /www/web/default/framework/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /www/web/default/framework/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /www/web/default/framework/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /www/web/default/appadmin/protected/controllers/SiteController.php(114): CModel->validate()
#14 /www/web/default/framework/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /www/web/default/framework/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /www/web/default/framework/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /www/web/default/framework/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /www/web/default/framework/yii/framework/web/CWebApplication.php(282): CController->run('login')
#19 /www/web/default/framework/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#20 /www/web/default/framework/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /www/web/default/appadmin/index.php(18): CApplication->run()
#22 {main}
REQUEST_URI=/appadmin/
HTTP_REFERER=http://sigwine.com/appadmin/
---
2015/11/25 17:16:25 [error] [exception.CDbException] could not find driver
2015/11/25 17:16:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in /www/web/default/framework/yii/framework/db/CDbConnection.php:387
Stack trace:
#0 /www/web/default/framework/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /www/web/default/framework/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /www/web/default/framework/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /www/web/default/framework/yii/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /www/web/default/framework/yii/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(UserMaster))
#7 /www/web/default/appadmin/protected/models/UserMaster.php(127): CActiveRecord::model('UserMaster')
#8 /www/web/default/appadmin/protected/components/UserIdentity.php(22): UserMaster::model()
#9 /www/web/default/appadmin/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /www/web/default/framework/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /www/web/default/framework/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /www/web/default/framework/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /www/web/default/appadmin/protected/controllers/SiteController.php(114): CModel->validate()
#14 /www/web/default/framework/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /www/web/default/framework/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /www/web/default/framework/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /www/web/default/framework/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /www/web/default/framework/yii/framework/web/CWebApplication.php(282): CController->run('login')
#19 /www/web/default/framework/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#20 /www/web/default/framework/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /www/web/default/appadmin/index.php(18): CApplication->run()
#22 {main}
REQUEST_URI=/appadmin/
HTTP_REFERER=http://sigwine.com/appadmin/
---
